# Generated by Django 3.1.1 on 2020-12-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('count', models.IntegerField(default=10)),
                ('stars', models.IntegerField(default=0)),
                ('cover', models.ImageField(blank=True, default='default_book.png', null=True, upload_to='books_cover')),
                ('authors', models.ManyToManyField(related_name='books', to='author.Author')),
            ],
        ),
    ]
