# Generated by Django 3.1.1 on 2020-12-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20201225_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='default_book.png', null=True, upload_to='books_cover'),
        ),
    ]
